# index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
    path: /deconnexion


# login:
#     path: /connexion
#     controller: App\Controller\SecurityController::login

# register:
#     path: /register
#     controller: src\Controller\RegistrationController::register

